parameters:
#    syrup_core.example.class: Syrup\CoreBundle\Example

services:
#    syrup_core.example:
#        class: %syrup_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
